import { Category, Platform, Sample } from './types';

export const CATEGORY_OPTIONS = Object.values(Category);
export const PLATFORM_OPTIONS = Object.values(Platform);

export const MOCK_SAMPLES: Sample[] = [
  {
    id: '1',
    name: '高保湿面霜 50ml',
    brandName: '科颜氏',
    imageUrl: 'https://picsum.photos/200/200?random=1',
    category: Category.Beauty,
    entryDate: '2023-10-25',
    locationCode: 'A-04-12',
    stockQuantity: 45,
    trackingNumber: 'SF1357924680',
    price: 299,
    commissionRate: 25,
    mechanism: '买一送一 (同款小样)',
    platform: [Platform.Douyin, Platform.Kuaishou],
    selectionCount: 12,
    specs: '50ml / 罐',
    businessContact: '王大力',
    merchantContact: '李经理',
    merchantPhone: '13800138000',
    procurementPrice: 180,
    includeShippingFee: true,
    isFreeShipping: true,
    assistantAnchor: '小美',
    remarks: '重点推荐品！质检报告已上传。参考链接：https://www.kiehls.com.cn',
    remarkImages: ['https://picsum.photos/200/200?random=101', 'https://picsum.photos/200/200?random=102']
  },
  {
    id: '2',
    name: '麻辣小龙虾尾 250g',
    brandName: '信良记',
    imageUrl: 'https://picsum.photos/200/200?random=2',
    category: Category.Food,
    entryDate: '2023-10-26',
    locationCode: 'B-02-05',
    stockQuantity: 120,
    trackingNumber: 'JD00987654321',
    price: 39.9,
    commissionRate: 15,
    mechanism: '拍2发3',
    platform: [Platform.Kuaishou],
    selectionCount: 8,
    specs: '250g / 盒',
    businessContact: '赵敏',
    merchantContact: '张老板',
    merchantPhone: '13912345678',
    procurementPrice: 25,
    includeShippingFee: false,
    isFreeShipping: false,
    assistantAnchor: '阿强',
    remarks: '注意保存温度，必须冷冻。',
    remarkImages: []
  },
  {
    id: '3',
    name: '纯棉宽松T恤 白色',
    brandName: '优衣库',
    imageUrl: 'https://picsum.photos/200/200?random=3',
    category: Category.Clothing,
    entryDate: '2023-10-24',
    locationCode: 'C-10-01',
    stockQuantity: 200,
    trackingNumber: 'YT888666555',
    price: 59,
    commissionRate: 30,
    mechanism: '两件9折',
    platform: [Platform.Douyin, Platform.Taobao],
    selectionCount: 35,
    specs: 'L码 / 白色',
    businessContact: '王大力',
    merchantContact: '周厂长',
    merchantPhone: '13766668888',
    procurementPrice: 28,
    includeShippingFee: true,
    isFreeShipping: true,
    assistantAnchor: '小美'
  },
  {
    id: '4',
    name: '和田玉吊坠 平安扣',
    brandName: '周大福',
    imageUrl: 'https://picsum.photos/200/200?random=4',
    category: Category.Jewelry,
    entryDate: '2023-10-20',
    locationCode: 'S-01-01', // S for Safe
    stockQuantity: 5,
    trackingNumber: 'SF999888777',
    price: 1288,
    commissionRate: 10,
    mechanism: '送礼盒+证书',
    platform: [Platform.Video号, Platform.PrivateDomain],
    selectionCount: 3,
    specs: '直径20mm',
    businessContact: 'Lisa',
    merchantContact: '陈总',
    merchantPhone: '18888888888',
    procurementPrice: 800,
    includeShippingFee: true,
    isFreeShipping: true,
    assistantAnchor: 'Coco'
  },
  {
    id: '5',
    name: '无线蓝牙降噪耳机',
    brandName: 'Sony',
    imageUrl: 'https://picsum.photos/200/200?random=5',
    category: Category.Electronics,
    entryDate: '2023-10-27',
    locationCode: 'D-05-08',
    stockQuantity: 30,
    trackingNumber: 'ZTO11223344',
    price: 199,
    commissionRate: 20,
    mechanism: '主要推品',
    platform: [Platform.Taobao, Platform.Pinduoduo],
    selectionCount: 15,
    specs: '黑色 / 标准版',
    businessContact: 'Steven',
    merchantContact: '刘工',
    merchantPhone: '13600001111',
    procurementPrice: 120,
    includeShippingFee: false,
    isFreeShipping: true,
    assistantAnchor: '小黑'
  },
  {
    id: '6',
    name: '运动即食鸡胸肉',
    brandName: '鲨鱼菲特',
    imageUrl: 'https://picsum.photos/200/200?random=6',
    category: Category.Food,
    entryDate: '2023-10-27',
    locationCode: 'B-03-02',
    stockQuantity: 500,
    trackingNumber: 'YUNDA556677',
    price: 9.9,
    commissionRate: 10,
    mechanism: '9.9元/3袋',
    platform: [Platform.Douyin],
    selectionCount: 50,
    specs: '100g / 袋',
    businessContact: '赵敏',
    merchantContact: '吴经理',
    merchantPhone: '15012341234',
    procurementPrice: 6.5,
    includeShippingFee: true,
    isFreeShipping: false,
    assistantAnchor: '阿强'
  }
];